dataset: "LJSpeech"

path:
  corpus_path: "/home/keon/speech-datasets/en/LJSpeech-1.1"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "/ssd2/implementations/raw_data/LJSpeech_22k" #"./raw_data/LJSpeech"
  preprocessed_path: "./preprocessed_data/LJSpeech"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    trim_top_db: 23
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  
    pitch_type: "cwt" # support 'frame', 'ph', 'cwt'
    pitch_norm: "log" # support 'standard', 'log'
    pitch_norm_eps: 0.000000001
    pitch_ar: False
    with_f0: True
    with_f0cwt: True
    use_uv: True
    f0_unsup_mean: 214.26887557735233 # need to be updated after running preprocessor
    f0_unsup_std: 63.952911937350315 # need to be updated after running preprocessor
    f0_sup_mean: 214.31683793056987 # need to be updated after running preprocessor
    f0_sup_std: 63.97520977575227 # need to be updated after running preprocessor
    cwt_scales: -1
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  duration:
    beta_binomial_scaling_factor: 1.0
